data_type:
  value: benign
dataset:
  value: NF-CSE-CIC-IDS2018-v3
num_epochs:
  value: 100
learning_rate:
  value: 0.0001
weight_decay:
  value: 0.6
edim_out:
  value: 64
batch_size:
  value: 16384
nhops:
  value: 1
fanout:
  value: 32768
agg_type:
  value: mean
patience:
  value: 10
dropout:
  value: 0.5
fraction:
  value: 0.2