data_type:
  desc: null
  value: benign
dataset:
  desc: null
  value: NF-UNSW-NB15-v3
num_epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.6
edim_out:
  desc: null
  value: 96
batch_size:
  desc: null
  value: 16384
nhops:
  desc: null
  value: 1
fanout:
  desc: null
  value: 32768
agg_type:
  desc: null
  value: mean
patience:
  desc: null
  value: 10
dropout:
  desc: null
  value: 0.6
fraction:
  desc: null
  value: null
