data_type:
  desc: null
  value: benign
dataset:
  desc: null
  value: NF-UNSW-NB15-v2
num_epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 1.1e-05
weight_decay:
  desc: null
  value: 0.6
edim_out:
  desc: null
  value: 72
batch_size:
  desc: null
  value: 32768
nhops:
  desc: null
  value: 1
fanout:
  desc: null
  value: 32768
agg_type:
  desc: null
  value: mean
patience:
  desc: null
  value: 10
dropout:
  desc: null
  value: 0.75
fraction:
  desc: null
  value: null
