data_type:
  desc: null
  value: benign
dataset:
  desc: null
  value: NF-CSE-CIC-IDS2018-v3
num_epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 0.6
ae_weight_decay:
  desc: null
  value: 0.03986574357073468
edim_out:
  desc: null
  value: 64
batch_size:
  desc: null
  value: 16384
nhops:
  desc: null
  value: 1
fanout:
  desc: null
  value: 32768
agg_type:
  desc: null
  value: mean
num_layers:
  desc: null
  value: 1
mask_ratio:
  desc: null
  value: 0.15
patience:
  desc: null
  value: 20
ae_batch_size:
  desc: null
  value: 64
window_size:
  desc: null
  value: 512
step_percent:
  desc: null
  value: 1.0
ae_embedding_dim:
  desc: null
  value: 32
ae_dropout:
  desc: null
  value: 0.2
dropout:
  desc: null
  value: 0.5
positional_encoding:
  desc: null
  value: None
fraction:
  desc: null
  value: 0.2